import "./globals.css";
import { Tajawal } from "next/font/google";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";

const tajawal = Tajawal({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={tajawal.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
